[package]
name = "specs"
version = "0.9.5"
description = "Specs Parallel ECS"
readme = "README.md"
documentation = "https://docs.rs/specs/"
repository = "https://github.com/slide-rs/specs"
homepage = "https://slide-rs.github.io/specs-website/"
keywords = ["gamedev"]
categories = ["concurrency"]
license = "Apache-2.0"
authors = ["slide-rs hackers"]
exclude = ["bors.toml", ".travis.yml"]

[badges]
travis-ci = { repository = "slide-rs/specs" }

[dependencies]
atom = "0.3"
crossbeam = "0.2.10"
fnv = "1.0"
hibitset = "0.1.3"
mopa = "0.2"
shred = "0.4.3"
shred-derive = "0.3"
tuple_utils = "0.2"
rayon = "0.7.1"

futures = { version = "0.1.14", optional = true }
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }

# enable rudy via --features rudy
rudy = { version = "0.1", optional = true }

[features]
common = ["futures"]
serialize = ["serde", "serde_derive"]

[dev-dependencies]
cgmath =  { version = "0.14", features = ["eders"] }
rand = "0.3"
serde_json = "1.0"

[[example]]
name = "basic"

[[example]]
name = "full"

[[example]]
name = "common"
required-features = ["common"]

[[example]]
name = "serialize"
required-features = ["serialize"]

[workspace]
members = ["specs-derive"]
